### ISSUE TITLE
SHA3-256 Binary File Not Working?

### ISSUE THREAD

**Issue by cyberflashguru** [brainhub/SHA3IUF#3]
...
`	uint8_t buf[200];
	sha3_context c;
	const uint8_t *hash;
	unsigned int bytesRead=0;

	sha3_Init256(&c);
	FILE *file = fopen("C:\\test.zip", "rb");
	while ((bytesRead = fread(buf, 1, sizeof buf, file)))
	{
	    sha3_Update(&c, buf, bytesRead);
	}	
	hash = sha3_Finalize(&c);`

Your code gives the hash:

25387a10b3a6f2b0a8570f91b3266c2a97ec5c4ef9087123de2e60e3ec68fb55

That hash above is different from other tools I have tested:

7d5bbd014c5a7311496670037747d603a8fe1b00f34fc25559d9f51322f75bc0

http://www.freecodeformat.com/file-hash.php

Has your code been tested against binary files?

Thanks.

**Comment by brainhub** [comment]
The behavior with _files_ is orthogonal to this code. This code only "sees" _memory buffers_. 

I have double-checked one test vector this code uses against the standard Linux **sha3sum**. sha3sum matches results of this code.

In more details:

I have created a file with the content of the test vector from [line 536](https://github.com/brainhub/SHA3IUF/blob/772553bc76153afc7853fd7d7303ec852fceebdc/sha3.c#L536):

> $ xxd _
> 0000000: b771 d5ce f5d1 a41a 93d1 5643 d718 1d2a  .q........VC...*
> 0000010: 2ef0 a8e8 4d91 812f 20ed 21f1 47be f732  ....M../ .!.G..2
> 0000020: bf3a 60ef 4067 c373 4b85 bc8c d471 780f  .:...g.sK....qx.
> 0000030: 10dc 9e82 91b5 8339 a677 b960 218f 71e7  .......9.w.`!.q.
> 0000040: 93f2 797a ea34 9406 5128 2906 5d37 bb55  ..yz.4..Q().]7.U
> 0000050: ea79 6fa4 f56f d889 6b49 b2cd 19b4 3215  .yo..o..kI....2.
> 0000060: ad96 7c71 2b24 e503 2d06 5232 e02c 1274  ..|q+$..-.R2.,.t
> 0000070: 09d2 ed41 46b9 d75d 763d 52db 98d9 49d3  ...AF..]v=R...I.
> 0000080: b0fe d6a8 052f bb
 (135 bytes)

> $ uname -a
> Linux ivy 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> $ sha3sum -a 256 _
> a19eee92bb2097b64e823d597798aa18be9b7c736b8059abfd6779ac35ac81b5  _

This is exactly what  [line 555](https://github.com/brainhub/SHA3IUF/blob/772553bc76153afc7853fd7d7303ec852fceebdc/sha3.c#L555) uses as the expected hash value. 

The code in SHA3IUF and in Linux Fedora Core distribution agree on the hash value. The expected hash value, above, is published by NIST.

I then uploaded the same file to [site you gave](http://www.freecodeformat.com/file-hash.php). I "checked" the SHA3-256 and see: 

> SHA3-256 Hash	bd6f5492582a7c1b116304de28314df9fffe95b0da11af52fe9440a717a34859

This is different from the 3 sources references above. Please see the README for references to the test vectors.

(I would guess that the site you references uses the _original_ Keccak instantiation, which is slightly different from the _NIST_ instantiation of the Keccak. You might try to define the [SHA3_USE_KECCAK](https://github.com/brainhub/SHA3IUF/blob/772553bc76153afc7853fd7d7303ec852fceebdc/sha3.c#L367) macro to confirm this guess. I have not verified this claim. )

**Comment by brainhub** [comment]
You might try to define the [SHA3_USE_KECCAK macro](https://github.com/brainhub/SHA3IUF/blob/772553bc76153afc7853fd7d7303ec852fceebdc/sha3.c#L367) to confirm the above guess.

**Comment by cyberflashguru** [comment]
Excellent...I enabled the SHA3_USE_KECCAK macro and got the same hash as the other sites/tools:

  0000  7d 5b bd 01 4c 5a 73 11 49 66 70 03 77 47 d6 03  }[..LZs.Ifp.wG..
  0010  a8 fe 1b 00 f3 4f c2 55 59 d9 f5 13 22 f7 5b c0  .....O.UY...".[.

Thanks for very helpful code! :)

**Comment by brainhub** [comment]
Please note that I have updated this project to include `SHA3_FLAGS_KECCAK` initialization flag and -k option to `sha3sum` to be able to switch between NIST SHA-3 and original Keccak (used in Etherium blockchain) at run-time. [README.md](README.ms) explains this in more details.
