### ISSUE TITLE
Wrong hashing result on string "identity3()"

### ISSUE THREAD

**Issue by hway** [brainhub/SHA3IUF#4]
must produce  f00032def569b31e64ba9c6846671eab2395fea87915ab639291340bf42a47c3
produces         f000000000000000000000000000000000000000000000000000000000000000

**Comment by hway** [comment]
original keccak algorithm

**Comment by hway** [comment]
original keccak algorithm

**Comment by hway** [comment]
Sorry, memory mismanagement

**Comment by brainhub** [comment]
No problems. Thank you.
